theme: jekyll-theme-minimal
logo: /assets/img/logoooo.jpg
title: false
description: SiTandur (Sistem Informasi Tanduran) merupakan aplikasi berbasis desktop yang berguna sebagai platform pencatatan hasil panen. 
